import os
from lsst.ts.wep.Utility import getModulePath
from lsst.ts.wep.Utility import runProgram

# Set the needed path
modulePath = getModulePath()
includePath = os.path.join(modulePath, "include")
srcFilePath = os.path.join(modulePath, "src", "mathcwfs.cc")

# Build the pybind11 module
output = "mathcwfs"
argstring = f"-O3 -Wall -shared -std=c++11 -I{includePath} -fPIC "
argstring += f"`python3 -m pybind11 --includes` {srcFilePath} -o {output}"
argstring += "`python3-config --extension-suffix`"
runProgram("c++", argstring=argstring)
