import os
from lsst.ts.wep.Utility import getModulePath
from lsst.ts.wep.Utility import runProgram

# Get the needed path
modulePath = getModulePath()

setupFilePath = os.path.join(modulePath, "builder", "setup.py")
libPath = os.path.join(modulePath, "python", "lsst", "ts", "wep", "cwfs", "lib")

# Build the cython code
argstring = "%s build_ext --build-lib %s" % (setupFilePath, libPath)
runProgram("python", argstring=argstring)
